RV-Park-Reservation-System/Pages/Admin/Users/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ApplicationCore.Interfaces;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Identity;

namespace RV_Park_Reservation_System.Pages.Admin.Users
{
    public class DeleteModel : PageModel
    {
        public string UserID { get; set; }

        private readonly IUnitOfWork _unitOfWork;

        private readonly UserManager<Customer> _userManager;

        public DeleteModel(IUnitOfWork unitOfWork, UserManager<Customer> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;

        }


        public void OnGet(string ID)
        {
            if (ID != null)
            {
                UserID = ID;
                var customer = _unitOfWork.Customer.Get(u => u.Id == UserID);
                _unitOfWork.Customer.Delete(customer);
                Page();
            }
            else
            {
                RedirectToPage("/Admin/Users/Index");
            }

        }
    }
}

RV-Park-Reservation-System/Pages/Admin/Users/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Models;
using ApplicationCore.Interfaces;
using Infrastructure.Services;

namespace RV_Park_Reservation_System.Pages.Admin.User
{
    public class IndexModel : PageModel
    {
        private readonly UserManager<Customer> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        public IndexModel(UserManager<Customer> userManager, IUnitOfWork unitOfWork)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }
        public IEnumerable<Customer> ApplicationUsers { get; set; }
        public Dictionary<string, List<string>> UserRoles { get; set; }
        public bool Success { get; set; }
        public string Message { get; set; }

        public async Task<IActionResult> OnGetAsync(bool success = false, string message = null)
        {
            if (!User.Identity.IsAuthenticated || User.IsInRole(SD.CustomerRole) || User.IsInRole(SD.EmployeeRole))
            {
                return RedirectToPage("/Shared/Prohibited", new { path = "/Admin/Users/Index" });
            }

            Success = success;
            Message = message;
            UserRoles = new Dictionary<string, List<string>>();
            ApplicationUsers = await _unitOfWork.Customer.ListAsync(a => a.Id != null);
            foreach (var user in ApplicationUsers)
            {
                var userRole = await _userManager.GetRolesAsync(user);
                UserRoles.Add(user.Id, userRole.ToList());
            }

            return Page();
        }
        public async Task<IActionResult> OnPostLockUnlock(string id)
        {
            var user = await _unitOfWork.Customer.GetAsync(u => u.Id == id);
            if (user.LockoutEnd == null)
            {
                user.LockoutEnd = DateTime.Now.AddYears(100);
            }
            else if (user.LockoutEnd > DateTime.Now)
            {
                user.LockoutEnd = DateTime.Now;
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(100);
            }
             _unitOfWork.Customer.Update(user);
            await _unitOfWork.CommitAsync();
            return RedirectToPage();
        }
    }
}

RV-Park-Reservation-System/Pages/Admin/Users/Update.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ApplicationCore.Interfaces;
using Infrastructure.Services;

namespace RV_Park_Reservation_System.Pages.Admin.User
{
    public class UpdateModel : PageModel
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<Customer> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UpdateModel(IUnitOfWork unitOfWork, UserManager<Customer> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        [BindProperty]
        public Customer AppUser { get; set; }

        public List<string> UsersRoles { get; set; }
        public List<string> AllRoles { get; set; }

        public List<string> OldRoles { get; set; }
        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (!User.Identity.IsAuthenticated || User.IsInRole(SD.CustomerRole) || User.IsInRole(SD.EmployeeRole))
            {
                return RedirectToPage("/Shared/Prohibited", new { path = "/Admin/Users/Index" });
            }

            AppUser = _unitOfWork.Customer.Get(u => u.Id == id); //gets the user from the ASPNetUser table (single row) and places in object AppUser
            var roles = await _userManager.GetRolesAsync(AppUser); //this retrieves the roles from the ASPNetUserRoles table (single row) and places them in roles object. 
            UsersRoles = roles.ToList(); //cast roles object to string list
            OldRoles = roles.ToList(); //cast roles object to string list
            AllRoles = _roleManager.Roles.Select(r => r.Name).ToList(); //gets all possible roles and stores them in string list

            return Page();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var newRoles = Request.Form["roles"]; //grabs all roles visible on the html page
            UsersRoles = newRoles.ToList(); //cast the user roles to a string list
            var oldRoles = await _userManager.GetRolesAsync(AppUser); //gets the user's roles from the ASPNetUserRoles Table (old ones)
            OldRoles = oldRoles.ToList(); //cast old roles to string list
            var rolesToAdd = new List<string>(); //creates new string list for which roles need to be added to the ASPNetUserRoles table. 
            var user = _unitOfWork.Customer.Get(u => u.Id == AppUser.Id); //gets the user from the ASPNetUser table through the Client model
            user.CustFirstName = AppUser.CustFirstName; //updates firstname 
            user.CustLastName = AppUser.CustLastName; //updates lastname 
            user.Email = AppUser.Email; //updates email address
            user.PhoneNumber = AppUser.PhoneNumber; //updates phone number
            _unitOfWork.Customer.Update(user); //updates the entire user object
            _unitOfWork.Commit(); //commits the changed user data to the ASPNetUser table 

            foreach (var r in UsersRoles)  //loops through the string list UserRoles (the currently assigned roles)
            {
                if (!OldRoles.Contains(r)) //if the role is NOT contained in the oldRoles, add it to the rolesToAdd string list
                {
                    rolesToAdd.Add(r); //adds the new roles (stored in r) to the rolesToAdd list
                }
            }
            foreach (var r in OldRoles) //loops through string list of OldRoles. 
            {
                if (!UsersRoles.Contains(r)) //if the new list of roles UserRoles does NOT contain the current role (r), remove it from the user.
                {
                    var result = await _userManager.RemoveFromRoleAsync(user, r); //removes old roles from the user (based on values in oldRoles)
                }
            }
            var result1 = await _userManager.AddToRolesAsync(user, rolesToAdd.AsEnumerable()); //Adds the roles to the userManager Roles table
            return RedirectToPage("./Index", new { success = true, message = "Update Successful" }); //return to the page
        }
    }
}

RV-Park-Reservation-System/Pages/Admin/Users/Delete.cshtml
@page
@model RV_Park_Reservation_System.Pages.Admin.Users.DeleteModel
@{
}


<h1> User Sucessfully Deleted !!!  </h1>

<li class="nav-item">
    <a class="btn btn-success text-light" asp-page="/Admin/Users/Index"><i class="far fa-edit"></i> List of Users</a>
</li>

RV-Park-Reservation-System/Pages/Admin/Users/Index.cshtml
@page
@model RV_Park_Reservation_System.Pages.Admin.User.IndexModel
@{
}

<div class="container">
    <h1 class="display-4 text-center text-primary my-5">USERS</h1>
    <div class="border backgroundWhite my-5 p-3">
        <div class="row mt-3">
            <div class="col-12 text-right">
                <a asp-page="/Account/Register" asp-area="Identity" class="btn btn-primary"><i class="fas fa-plus"></i> &nbsp; Add User</a>
            </div>
        </div>
        <br /><br />
        <p style="display: none;" id="success">@Model.Success.ToString()</p>
        <p class="hidden" id="message">@Model.Message</p>
        <div class="dataTables_wrapper">
            <table class="table table-striped table-bordered display" style="width:100%" id="DTusers" >
                <thead>
                    <tr>
                        <th scope="col">Full Name</th>
                        <th scope="col">E-Mail</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Role(s)</th>
                        <th scope="col">Lock/Unlock</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var user in Model.ApplicationUsers)
                        {
                            <tr>
                                <td>@user.CustFirstName @user.CustLastName</td>
                                <td>@user.Email</td>
                                <td>@user.PhoneNumber</td>
                                <td>
                                    @{
                                        if (Model.UserRoles[user.Id].Count() == 1)
                                        {
                                            @Model.UserRoles[user.Id].First()
                                        }
                                        else
                                        {
                                            <ul>
                                                @{
                                                    foreach (var r in Model.UserRoles[user.Id])
                                                    {
                                                        <li>
                                                            @r
                                                        </li>
                                                    }
                                                }
                                            </ul>
                                        }
                                    }
                                </td>
                                <td>
                                    <form method="post">
                                        @{
                                            if (user.LockoutEnd > DateTime.Now)
                                            {
                                                <button type="submit" class="btn btn-warning text-dark" asp-page-handler="lockUnlock" asp-route-id="@user.Id"><i class="fas fa-lock-open"></i> Unlock</button>
                                            }
                                            else
                                            {
                                                <button type="submit" class="btn btn-warning text-dark" asp-page-handler="lockUnlock" asp-route-id="@user.Id"><i class="fas fa-lock"></i> Lock</button>
                                            }
                                        }
                                    </form>
                                </td>
                                <td>
                                    <a class="btn btn-success text-light" asp-page="/Admin/Users/Update" asp-route-id="@user.Id"><i class="far fa-edit"></i> Edit</a>
                                    @*<a class="btn btn-danger text-light" asp-page="/Admin/Users/Delete" asp-route-id="@user.Id"><i class="far fa-trash-alt"></i> Delete</a>*@
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        function alertFunc() {
            var success = $("#success").html()
            var message = $("#message").html();
            console.log(success);
            console.log(message);
            if (success == "True") {
                toastr.success(message);
            };

        }
        window.onload = alertFunc();

        $(document).ready(function () {
            let dTable = $('#DTusers').DataTable({
                ordering: true,
                order: [[0, "asc"]],
                paging: true,
                bfilter: true
            });
        });
    </script>
}

RV-Park-Reservation-System/Pages/Admin/Users/Update.cshtml
@page
@model RV_Park_Reservation_System.Pages.Admin.User.UpdateModel
@{
}
<div class="container">
    <form class="form" method="post">
        <div class="row">
            <input type="hidden" value="@Model.AppUser.Id" asp-for="@Model.AppUser.Id" />
            <input type="hidden" value="@Model.OldRoles.ToList()" asp-for="@Model.OldRoles" />
            <div class="form-group col-md-6">
                <label asp-for="@Model.AppUser.CustFirstName">First Name</label>
                <input class="form-control" asp-for="@Model.AppUser.CustFirstName" value="@Model.AppUser.CustFirstName" />
            </div>
            <div class="form-group col-md-6">
                <label asp-for="@Model.AppUser.CustLastName">Last Name</label>
                <input class="form-control" asp-for="@Model.AppUser.CustLastName" value="@Model.AppUser.CustLastName" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.AppUser.Email">Email</label>
                <input class="form-control" asp-for="@Model.AppUser.Email" value="@Model.AppUser.Email" />
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                <label asp-for="@Model.AppUser.PhoneNumber">Phone Number</label>
                <input class="form-control" asp-for="@Model.AppUser.PhoneNumber" value="@Model.AppUser.PhoneNumber" />
            </div>
        </div>
        @{
            foreach (var r in Model.AllRoles)
            {
                <div class="form-check">
                    @{
                        if (Model.UsersRoles.Contains(r))
                        {
                            <input class="form-check-input" name="roles" type="radio" id="@r" value="@r" checked>
                            <label class="form-check-label">@r</label>
                        }
                        else
                        {
                            <input class="form-check-input" name="roles" type="radio" id="@r" value="@r">
                            <label class="form-check-label">@r</label>
                        }
                    }
                </div>
            }
        }
        <button type="submit">Update</button>
    </form>
</div>